config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :create, :edit, :show, :update, :destroy]
  match 'index' => "home#index", via: [:get]
  resources :ocorrencia do
    resources :comments, module: :ocorrencia
  end
  resources :termo_compromissos do
    resources :comments, module: :termo_compromissos
    member do
      # /agreements/:id/export
      get 'export'
    end
  end
  resources :manutencaos do
    resources :comments, module: :manutencaos
  end
  resources :estoque_pecas do
    get 'filed', on: :collection
    match 'arquivar' => "estoque_pecas#arquivar_peca", via: [:get]
    resources :comments, module: :estoque_pecas
  end
  resources :pecas do
    resources :comments, module: :pecas
  end
  resources :modelos do
    resources :comments, module: :modelos
  end
  resources :equipamentos do
  	match 'manutencaos' => "equipamentos#manutencao", via: [:get]
    resources :comments, module: :equipamentos
  end
  resources :servidors do 
    resources :comments, module: :servidors
  end
  resources :comments

  root "home#index"
end

app/models/estoque_peca.rb
class EstoquePeca < ApplicationRecord
	belongs_to :equipamento
	belongs_to :peca
	has_many :comments, as: :commentable
end

app/controllers/estoque_pecas/comments_controller.rb
class EstoquePecas::CommentsController < CommentsController
	before_action :set_commentable

	private
		def set_commentable
			@commentable = EstoquePeca.find(params[:estoque_peca_id])
		end
end

app/controllers/estoque_pecas_controller.rb
class EstoquePecasController < ApplicationController
  load_and_authorize_resource
  before_action :set_estoque_peca, only: [:show, :edit, :update, :destroy]

  # GET /estoque_pecas
  # GET /estoque_pecas.json
  def index
    @estoque_pecas = EstoquePeca.where("status = 'Disponível'").page(params[:page]).per(10)
  end

  def filed
    @estoque_pecas = EstoquePeca.where("status = 'Utilizada'").page(params[:page]).per(10)
  end

  # GET /estoque_pecas/1
  # GET /estoque_pecas/1.json
  def show
    @comments = @estoque_peca.comments.order("id DESC").page(params[:page]).per(3)
  end

  # GET /estoque_pecas/new
  def new
    @estoque_peca = EstoquePeca.new
  end

  # GET /estoque_pecas/1/edit
  def edit
  end

  # POST /estoque_pecas
  # POST /estoque_pecas.json
  def create
    @estoque_peca = EstoquePeca.new(estoque_peca_params)

    respond_to do |format|
      if @estoque_peca.save
        format.html { redirect_to @estoque_peca, notice: 'Estoque peca was successfully created.' }
        format.json { render :show, status: :created, location: @estoque_peca }
      else
        format.html { render :new }
        format.json { render json: @estoque_peca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estoque_pecas/1
  # PATCH/PUT /estoque_pecas/1.json
  def update
    respond_to do |format|
      if @estoque_peca.update(estoque_peca_params)
        format.html { redirect_to @estoque_peca, notice: 'Estoque peca was successfully updated.' }
        format.json { render :show, status: :ok, location: @estoque_peca }
      else
        format.html { render :edit }
        format.json { render json: @estoque_peca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estoque_pecas/1
  # DELETE /estoque_pecas/1.json
  def destroy
    @estoque_peca.destroy
    respond_to do |format|
      format.html { redirect_to estoque_pecas_url, notice: 'Estoque peca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estoque_peca
      @estoque_peca = EstoquePeca.find(params[:id])
    end

    def get_estoque_peca

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estoque_peca_params
      params.require(:estoque_peca).permit(:equipamento_id, :peca_id, :quantidade, :status)
    end
end

app/helpers/estoque_pecas_helper.rb
module EstoquePecasHelper
end

app/views/estoque_pecas/_form.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoInf">
<%= form_with(model: estoque_peca, local: true) do |form| %>
  <% if estoque_peca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estoque_peca.errors.count, "error") %> prohibited this estoque_peca from being saved:</h2>

      <ul>
      <% estoque_peca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6 col-sm-6 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :equipamento_id, 'Patrimônio' %><br>
      <%= form.collection_select :equipamento_id, Equipamento.where(status: 'Doador de Peças'), :id, :patrimonio, {}, {class: 'form-control'} %>
    </div>
  </div>

  <div class="col-md-6 col-sm-6 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :peca_id, 'Peca' %><br>
      <%= form.collection_select :peca_id, Peca.all, :id, :nome, {}, {class: 'form-control'} %>
    </div>
  </div>

  <div class="col-md-6 col-sm-6 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :status, 'Status' %><br>
      <%= form.select :status, ['Disponível', 'Utilizada'], {}, {class: 'form-control'} %>
    </div>
  </div>

  <div class="col-md-6 col-sm-6 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :quantidade, 'Quantidade' %><br>
      <%= form.select :quantidade, ['1', '2', '3', '4', '5', '6', '7', '8', '9'], {}, {class: 'form-control'} %>
    </div>
  </div>

<!--   <div class="col-md-4 col-sm-4 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :quantidade %>
      <%= form.text_field :quantidade, class: "form-control" %>
    </div>
  </div> -->

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <%= form.submit 'Salvar', class:"btn btn-default" %>
        <%= link_to 'Voltar', estoque_pecas_path, class:"btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/estoque_pecas/edit.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
    <h1>Editar Estoque de Peças</h1>
</div>

<%= render 'form', estoque_peca: @estoque_peca %>

app/views/estoque_pecas/filed.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
  <h1>Estoque de Peças</h1>
</div>

<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoInf">
  <div class="col-md-8 col-md-offset-4 col-sm-10 col-sm-offset-2 col-xs-12 text-right">
        <%= link_to 'Novo Estoque de Peça', new_estoque_peca_path, class:"btn btn-default" %>
        <%= link_to 'Peças Disponíveis', estoque_pecas_path, class:"btn btn-default" %>
    </div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="table-responsive">
          <table class="table table-hover">
            <% if @estoque_pecas.empty? %>
              <p> Não há uso de peça registrado </p>
            <% else %>
              <thead>
                <tr>
                  <th>Equipamento</th>
                  <th>Peça</th>
                  <th>Status</th>
                  <th>Quantidade</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @estoque_pecas.each do |estoque_peca| %>
                  <tr>
                    <td><%= link_to estoque_peca.equipamento.patrimonio, equipamento_path("#{estoque_peca.equipamento_id}") %></td>
                    <td>
                      <%= link_to estoque_peca.peca.nome + ' - ' + estoque_peca.peca.caracteristica, peca_path("#{estoque_peca.peca_id}") %>
                    </td>
                    <td><%= estoque_peca.status %></td>
                    <td><%= estoque_peca.quantidade %></td>
                    <td><%= link_to 'Detalhes', estoque_peca, class: "btn-sm btn-info" %></td>
                    <td><%= link_to 'Editar', edit_estoque_peca_path(estoque_peca), class: "btn-sm btn-default" %></td>
                    <td><%= link_to 'Deletar', estoque_peca, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn-sm btn-danger" %></td>
                  </tr>
                <% end %>
              </tbody>
            <% end %>
          </table>
          <%= paginate @estoque_pecas, window: 2 %>
        </div>
      </div>
    </div>
</div>

app/views/estoque_pecas/index.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
  <h1>Estoque de Peças</h1>
</div>

<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoInf">
    <div class="col-md-8 col-md-offset-4 col-sm-10 col-sm-offset-2 col-xs-12 text-right">
      <div class="form-group">
      <% if can? :create, EstoquePeca %>
        <%= link_to 'Novo Estoque de Peça', new_estoque_peca_path, class:"btn btn-default" %>
      <% end %>
      <%= link_to 'Peças Utilizadas', filed_estoque_pecas_path, class:"btn btn-default" %>
    </div>
    </div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
          <caption>Estoque</caption>
            <tr>
              <th>Equipamento</th>
              <th>Peça</th>
              <th>Status</th>
              <th>Quantidade</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @estoque_pecas.each do |estoque_peca| %>
              <tr>
                <td><%= link_to estoque_peca.equipamento.patrimonio, equipamento_path("#{estoque_peca.equipamento_id}") %></td>
                <td>
                  <%= link_to estoque_peca.peca.nome + ' - ' + estoque_peca.peca.caracteristica, peca_path("#{estoque_peca.peca_id}") %>
                </td>
                <td><%= estoque_peca.status %></td>
                <td><%= estoque_peca.quantidade %></td>
                <td><%= link_to 'Detalhes', estoque_peca, class: "btn-sm btn-info" %></td>
                <td><%= link_to 'Editar', edit_estoque_peca_path(estoque_peca), class: "btn-sm btn-default" %></td>
                <td><%= link_to 'Deletar', estoque_peca, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn-sm btn-danger" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @estoque_pecas, window: 2 %>
      </div>
    </div>
  </div>
</div>

app/views/estoque_pecas/new.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
    <h1>Novo Estoque de Peça</h1>
</div>

<%= render 'form', estoque_peca: @estoque_peca %>

app/views/estoque_pecas/show.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoSup">
  <p>
    <strong>Equipamento:</strong>
    <%= @estoque_peca.equipamento.patrimonio %>
  </p>

  <p>
    <strong>Peça:</strong>
    <%= @estoque_peca.peca.nome + ' - ' + @estoque_peca.peca.caracteristica %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @estoque_peca.status %>
  </p>

  <p>
  	<strong>Quantidade:</strong>
  	<%= @estoque_peca.quantidade %>
  </p>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <%= link_to 'Editar', edit_estoque_peca_path(@estoque_peca), class:"btn btn-primary"%>
      <%= link_to 'Voltar', estoque_pecas_path, class:"btn btn-default"%>
    </div>
  </div>

  <h3>Comentários</h3>
  <% @comments.each do |comment| %>
    <div class="well">
      <%= comment.user.name %> - <%= comment.created_at %> - 
      <% if current_user.id == comment.user.id %>
        <%= link_to 'Apagar', comment, method: :delete, data: { confirm: 'Tem certeza?' } %>
      <% end %>
      <p>
      <%= comment.body %>
    </div>
  <% end %>
  <%= paginate @comments, window: 2 %>

  <%= render partial: "comments/form", locals: {commentable: @estoque_peca} %>
  <!-- <%= render partial: "comments/comments", locals: {commentable: @estoque_peca} %>-->
</div>