config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :create, :edit, :show, :update, :destroy]
  match 'index' => "home#index", via: [:get]
  resources :ocorrencia do
    resources :comments, module: :ocorrencia
  end
  resources :termo_compromissos do
    resources :comments, module: :termo_compromissos
    member do
      # /agreements/:id/export
      get 'export'
    end
  end
  resources :manutencaos do
    resources :comments, module: :manutencaos
  end
  resources :estoque_pecas do
    get 'filed', on: :collection
    match 'arquivar' => "estoque_pecas#arquivar_peca", via: [:get]
    resources :comments, module: :estoque_pecas
  end
  resources :pecas do
    resources :comments, module: :pecas
  end
  resources :modelos do
    resources :comments, module: :modelos
  end
  resources :equipamentos do
  	match 'manutencaos' => "equipamentos#manutencao", via: [:get]
    resources :comments, module: :equipamentos
  end
  resources :servidors do 
    resources :comments, module: :servidors
  end
  resources :comments

  root "home#index"
end

app/models/equipamento.rb
class Equipamento < ApplicationRecord
	belongs_to :modelo
	has_many :estoque_pecas, dependent: :restrict_with_exception
	has_many :pecas, :through => :estoque_pecas
	has_many :manutencaos
	has_many :servidors, :through => :termo_compromisso
	has_many :termo_compromisso, dependent: :restrict_with_exception
	has_many :comments, as: :commentable

	def self.search(search)
	    if search
	      where(['patrimonio LIKE ?', "%#{search}%"])
	    else
	      all
	    end
  	end

  	def self.notebook_disponivel
  		# Buscar equipamentos disponíveis que o tipo do modelo seja um notebook
		joins(:modelo).where(:modelos => {tipo: 'Notebook'}, status: 'Disponível')
  	end

  	def self.tablet_disponivel
		joins(:modelo).where(:modelos => {tipo: 'Tablet'}, status: 'Disponível')
  	end
end

app/controllers/equipamentos/comments_controller.rb
class Equipamentos::CommentsController < CommentsController
	before_action :set_commentable

	private
		def set_commentable
			@commentable = Equipamento.find(params[:equipamento_id])
		end
end

app/controllers/equipamentos_controller.rb
class EquipamentosController < ApplicationController
  load_and_authorize_resource
  before_action :set_equipamento, only: [:show, :edit, :update, :destroy]

  # GET /equipamentos
  # GET /equipamentos.json
  def index
    # @equipamentos = Equipamento.all
    # @equipamentos = Equipamento.search(params[:search]).page(params[:page]).per(2)
    @equipamentos = Equipamento.search(params[:search]).order(:patrimonio).page(params[:page]).per(10)
  end

  # GET /equipamentos/1
  # GET /equipamentos/1.json
  def show
    @comments = @equipamento.comments.order("id DESC").page(params[:page]).per(3)
  end

  def manutencao
    @equipamento = Equipamento.find(params[:equipamento_id])
    @equipamento_manutencaos = Manutencao.where(["equipamento_id = ?", params[:equipamento_id]]).order(:numOrdem).page(params[:page]).per(10)
  end

  # GET /equipamentos/new
  def new
    @equipamento = Equipamento.new
  end

  # GET /equipamentos/1/edit
  def edit
  end

  # POST /equipamentos
  # POST /equipamentos.json
  def create
    @equipamento = Equipamento.new(equipamento_params)

    respond_to do |format|
      if @equipamento.save
        format.html { redirect_to @equipamento, notice: 'Equipamento foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @equipamento }
      else
        format.html { render :new }
        format.json { render json: @equipamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipamentos/1
  # PATCH/PUT /equipamentos/1.json
  def update
    respond_to do |format|
      if @equipamento.update(equipamento_params)
        format.html { redirect_to @equipamento, notice: 'Equipamento foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @equipamento }
      else
        format.html { render :edit }
        format.json { render json: @equipamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipamentos/1
  # DELETE /equipamentos/1.json
  def destroy
    begin
      @equipamento.destroy
      # flash[:success] = "successfully destroyed."
      respond_to do |format|
        format.html { redirect_to equipamentos_url, notice: 'Equipamento foi excluído com sucesso' }
        format.json { head :no_content }
      end
    rescue ActiveRecord::DeleteRestrictionError => e
      @equipamento.errors.add(:base, e)
      # flash[:error] = "#{e}"
      respond_to do |format|
        format.html { redirect_to equipamentos_url, notice: 'Equipamnto não pode ser destruído. Há alguma dependência.' }
        format.json { head :no_content }
      end
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipamento
      @equipamento = Equipamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipamento_params
      params.require(:equipamento).permit(:id, :patrimonio, :serial, :dataAquisicao, :status, :modelo_id)
    end
end

app/helpers/equipamentos_helper.rb
module EquipamentosHelper
end

app/views/equipamentos/_form.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoInf">
<%= form_with(model: equipamento, local: true) do |form| %>
  <% if equipamento.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% equipamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="col-md-4 col-sm-6 col-xs-12 text-left">
          <div class="form-group" >
            <%= form.label :tipo, 'Tipo do Equipamento' %><br />
            <label for="equipamento[tipo]" class="radio-inline"><%= form.radio_button :tipo, 'Notebook', id:'note', :checked => true %>Notebook</label>
            <label for="equipamento[tipo]" class="radio-inline"><%= form.radio_button :tipo, 'Tablet', id:'tablet'%>Tablet</label>
          </div>
        </div>
      </div>
    </div>
    
    <div id="noteSelect" class="col-md-4 col-sm-4 col-xs-12 text-left">
      <div class="form-group">
        <%= form.label :modelo_id, 'Modelo' %>
        <%= form.collection_select :modelo_id, Modelo.where(tipo: 'Notebook'), :id, :marca, {}, {class: 'form-control'} %>
      </div>
    </div>
  
    <div id="tabletSelect" class="hidden-lg hidden-md hidden-sm hidden-xs text-left">
      <div class="form-group">
        <%= form.label :modelo_id, 'Modelo' %>
        <%= form.collection_select :modelo_id, Modelo.where(tipo: 'Tablet'), :id, :marca, {}, {class: 'form-control'} %>
      </div>
    </div>

  <div class="col-md-4 col-sm-4 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :patrimonio %>
      <%= form.text_field :patrimonio, class: "form-control" %>
    </div>
  </div>

  <div class="col-md-4 col-sm-4 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :serial %>
      <%= form.text_field :serial, class: "form-control" %>
    </div>
  </div>

  <div class="col-md-4 col-sm-4 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :status, 'Status' %>
      <%= form.select :status, ['Disponível', 'Vinculado', 'Transferido', 'Desaparecido', 'Furtado', 'Inutilizável', 'Doador de Peças', 'Em Manutenção'], {}, {class: 'form-control'} %>
    </div>
  </div>

<!--   <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="col-md-4 col-sm-4 col-xs-12 text-left">
        <div class="form-group">
          <%= form.label :tipo, 'Tipo do Equipamento' %><br />
          <label class="radio-inline"><%= form.radio_button :tipo, 'Notebook', :checked => true %>Notebook</label>
          <label class="radio-inline"><%= form.radio_button :tipo, 'Tablet' %>Tablet</label>
        </div>
      </div>
    </div>
  </div>
  
  <div class="col-md-4 col-sm-4 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :modelo_id, 'Modelo' %>
      <%= form.collection_select :modelo_id, Modelo.where(tipo: 'Notebook'), :id, :marca %>
    </div>
  </div> -->



  <div class="col-md-6 col-sm-6 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :dataAquisicao, 'Data de Aquisição' %>
      <%= form.date_select :dataAquisicao, :start_year => Date.current.year, :end_year => 2010 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <%= form.submit 'Salvar', class:"btn btn-primary" %>
        <%= link_to 'Voltar', "javascript:window.history.go(-1)", class:"btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>
</div>

<script>
  $( document ).ready(function() {
    Htmlnote = $( "#noteSelect" );
    Htmltablet = $( "#tabletSelect" );
    $( "#tabletSelect" ).remove();
  });

  $( "#note" ).click(function() {
    if($( "#note" ).prop("checked", true)){
      $( "#tabletSelect" ).before(Htmlnote);
      $( "#tabletSelect" ).remove();
    }
    });

  $( "#tablet" ).click(function() {
    if($( "#tablet" ).prop("checked", true)){
      $( "#noteSelect" ).before(Htmltablet);
      $( "#noteSelect" ).remove();
    }
  });
</script>

app/views/equipamentos/edit.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
    <h1>Editar Equipamento</h1>
</div>

<%= render 'form', equipamento: @equipamento %>

app/views/equipamentos/index.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
  <h1>Equipamentos</h1>
</div>

<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoInf">
  <div class="row">
    <div class="col-md-6 col-sm-8 col-xs-12">
      <div class="form-group">
              <%= form_tag equipamentos_path, :action => 'index', :method => 'get' do %>
                <%= 'Digite o patrimônio para buscar' %>
                <br>
                <%= text_field_tag :search, params[:search], :class => "form-control", :style => "width: initial;"%>
                <%= submit_tag "Buscar", :patrimonio => nil, :class => "btn btn-primary" %>
            <% end %>
            </div>
  </div>
    <div class="col-md-6 col-sm-4 col-xs-12 text-right">
      <div class="form-group">
      <% if can? :create, Equipamento %>
      <br>
        <%= link_to 'Novo Equipamento', new_equipamento_path, class:"btn btn-default" %>
      <% end %>
    </div>

    </div>
  </div>



  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
          <caption>Equipamentos</caption>
            <tr>
              <th>Patrimônio</th>
              <th>Serial</th>
              <th>Data de aquisiçao</th>
              <th>Status</th>
              <th>Modelo</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @equipamentos.each do |equipamento| %>
              <tr>
                <td><%= link_to "#{equipamento.patrimonio}", equipamento %></td>
                <td><%= equipamento.serial %></td>
                <td><%= equipamento.dataAquisicao %></td>
                <td><%= equipamento.status %></td>
                <td><%= link_to equipamento.modelo.marca, modelo_path("#{equipamento.modelo_id}") %></td>
                <td><%= link_to 'Manutenções', equipamento_manutencaos_path(equipamento), class: "btn-sm btn-warning" %></td>
                <td><%= link_to 'Detalhes', equipamento, class: "btn-sm btn-info" %></td>
                <td><%= link_to 'Editar', edit_equipamento_path(equipamento), class: "btn-sm btn-default" %></td>
                <td><%= link_to 'Deletar', equipamento, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn-sm btn-danger" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @equipamentos, window: 2 %>
      </div>
    </div>
  </div>
</div>

app/views/equipamentos/manutencao.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-12">
  <p id="notice"><%= notice %></p>
  <h1>Manutenções do Patrimônio <%= @equipamento.patrimonio %></h1>
</div>

<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-12 conteudoInf">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="table-responsive">
        <table class="table table-hover">
          <% if @equipamento_manutencaos.empty? %>
            <p> Nenhuma manutenção registrada </p>
          <% else %>
            <thead>
            <caption>Manutenções</caption>
              <tr>
                <th>Numero de ordem</th>
                <th>Patrimônio</th>
                <th>Descrição</th>
                <th>Data de entrada</th>
                <th>Data de saída</th>
                <th>Status</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <% @equipamento_manutencaos.each do |manutencao| %>
                <tr>
                  <td><%= link_to "#{manutencao.numOrdem}", manutencao %></td>
                  <td><%= link_to manutencao.equipamento.patrimonio, equipamento_path("#{manutencao.equipamento_id}") %></td>
                  <td><%= manutencao.descricao %></td>
                  <td><%= manutencao.dataEntrada %></td>
                  <td><%= manutencao.dataSaida %></td>
                  <td><%= manutencao.status %></td>
                  <td><%= link_to 'Detalhes', manutencao, class: "btn-sm btn-info" %></td>
                  <td><%= link_to 'Editar', edit_manutencao_path(manutencao), class: "btn-sm btn-default" %></td>
                  <td><%= link_to 'Deletar', manutencao, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn-sm btn-danger" %></td>
                </tr>
              <% end %>
            </tbody>
          <% end %>
        </table>
        <%= paginate @equipamento_manutencaos, window: 2 %>
      </div>
    </div>
  </div>
</div>

app/views/equipamentos/new.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
    <h1>Novo Equipamento</h1>
</div>

<%= render 'form', equipamento: @equipamento %>

app/views/equipamentos/show.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoSup">
  <p>
    <strong>Patrimônio:</strong>
    <%= @equipamento.patrimonio %>
  </p>

  <p>
    <strong>Serial:</strong>
    <%= @equipamento.serial %>
  </p>

  <p>
    <strong>Data de Aquisição:</strong>
    <%= @equipamento.dataAquisicao.strftime("%d/%m/%Y") %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @equipamento.status %>
  </p>

  <p>
    <strong>Modelo:</strong>
    <%= link_to @equipamento.modelo.marca, modelo_path("#{@equipamento.modelo_id}") %>
  </p>

  <p>
    <% if @equipamento.status == "Doador de Peças"%>
      <strong>Peças Disponíveis:</strong>
      <br>
      <%= link_to '+', new_estoque_peca_path, class:"btn btn-default btn-sm" %>
      <% if @equipamento.estoque_pecas.empty? %>
        <p>Nenhuma peça disponíveis</p>
      <% else %>
        <table width="500px">
          <tr>
            <td>Peça</td>
            <td>Caracteristica</td>
            <td>Quantidade</td>
          </tr>
          <% @equipamento.estoque_pecas.each do |estoque_pecas| %>
            <tr>
              <td><%= link_to estoque_pecas.peca.nome, peca_path("#{estoque_pecas.peca_id}") %></td>
              <td><%= estoque_pecas.peca.caracteristica%></td>
              <td><%= estoque_pecas.quantidade %></td>
            </tr>
          <% end %>
        </table>
      <% end %>
    <% else %>

    <% end %>
  </p>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <%= link_to 'Editar', edit_equipamento_path(@equipamento), class:"btn btn-primary"%>
      <%= link_to 'Voltar', "javascript:window.history.go(-1)", class:"btn btn-default" %>
    </div>
  </div>

  <h2>Comentários</h2>
  <% @comments.each do |comment| %>
    <div class="well">
      <%= comment.user.name %> - <%= comment.created_at %> - 
      <% if current_user.id == comment.user.id %>
        <%= link_to 'Apagar', comment, method: :delete, data: { confirm: 'Tem certeza?' } %>
      <% end %>
      <p>
      <%= comment.body %>
    </div>
  <% end %>
  <%= paginate @comments, window: 2 %>

  <%= render partial: "comments/form", locals: {commentable: @equipamento} %>
  <!-- <%= render partial: "comments/comments", locals: {commentable: @equipamento} %>-->
</div>