config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :create, :edit, :show, :update, :destroy]
  match 'index' => "home#index", via: [:get]
  resources :ocorrencia do
    resources :comments, module: :ocorrencia
  end
  resources :termo_compromissos do
    resources :comments, module: :termo_compromissos
    member do
      # /agreements/:id/export
      get 'export'
    end
  end
  resources :manutencaos do
    resources :comments, module: :manutencaos
  end
  resources :estoque_pecas do
    get 'filed', on: :collection
    match 'arquivar' => "estoque_pecas#arquivar_peca", via: [:get]
    resources :comments, module: :estoque_pecas
  end
  resources :pecas do
    resources :comments, module: :pecas
  end
  resources :modelos do
    resources :comments, module: :modelos
  end
  resources :equipamentos do
  	match 'manutencaos' => "equipamentos#manutencao", via: [:get]
    resources :comments, module: :equipamentos
  end
  resources :servidors do 
    resources :comments, module: :servidors
  end
  resources :comments

  root "home#index"
end

app/models/peca.rb
class Peca < ApplicationRecord
	has_many :estoque_pecas, dependent: :restrict_with_exception
	has_many :equipamentos, :through => :estoque_pecas
	has_many :comments, as: :commentable

	def self.search(search)
	    if search
	      where(['nome LIKE ?', "%#{search}%"])
	    else
	      all
	    end
  	end
end

app/controllers/pecas/comments_controller.rb
class Pecas::CommentsController < CommentsController
	before_action :set_commentable

	private
		def set_commentable
			@commentable = Peca.find(params[:peca_id])
		end
end

app/controllers/pecas_controller.rb
class PecasController < ApplicationController
  load_and_authorize_resource
  before_action :set_peca, only: [:show, :edit, :update, :destroy]

  # GET /pecas
  # GET /pecas.json
  def index
    # @pecas = Peca.all
    @pecas = Peca.search(params[:search]).order(:nome).page(params[:page]).per(3)
  end

  # GET /pecas/1
  # GET /pecas/1.json
  def show
    @comments = @peca.comments.order("id DESC").page(params[:page]).per(3)
  end

  # GET /pecas/new
  def new
    @peca = Peca.new
  end

  # GET /pecas/1/edit
  def edit
  end

  # POST /pecas
  # POST /pecas.json
  def create
    @peca = Peca.new(peca_params)

    respond_to do |format|
      if @peca.save
        format.html { redirect_to @peca, notice: 'Peca was successfully created.' }
        format.json { render :show, status: :created, location: @peca }
      else
        format.html { render :new }
        format.json { render json: @peca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pecas/1
  # PATCH/PUT /pecas/1.json
  def update
    respond_to do |format|
      if @peca.update(peca_params)
        format.html { redirect_to @peca, notice: 'Peca was successfully updated.' }
        format.json { render :show, status: :ok, location: @peca }
      else
        format.html { render :edit }
        format.json { render json: @peca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pecas/1
  # DELETE /pecas/1.json
  def destroy
    begin
      @peca.destroy
      # flash[:success] = "successfully destroyed."
      respond_to do |format|
        format.html { redirect_to pecas_url, notice: 'Peca was successfully destroyed.' }
        format.json { head :no_content }
      end
    rescue ActiveRecord::DeleteRestrictionError => e
      @peca.errors.add(:base, e)
      # flash[:error] = "#{e}"
      respond_to do |format|
        format.html { redirect_to pecas_url, notice: 'Peca can not be destroyed. There is some dependency.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peca
      @peca = Peca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peca_params
      params.require(:peca).permit(:nome, :caracteristica)
    end
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/views/pecas/_form.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoInf">
  <div class="row">
<%= form_with(model: peca, local: true) do |form| %>
  <% if peca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peca.errors.count, "error") %> prohibited this peca from being saved:</h2>

      <ul>
      <% peca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-4 col-sm-4 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :nome %>
      <br>
      <%= form.text_field :nome, class: "form-control" %>
    </div>
  </div>

  <div class="col-md-4 col-sm-4 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :caracteristica %>
      <%= form.text_field :caracteristica, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <%= form.submit 'Salvar', class:"btn btn-primary" %>
        <%= link_to 'Voltar', pecas_path, class:"btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>
  </div>

app/views/pecas/edit.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
    <h1>Editar peca</h1>
</div>

<%= render 'form', peca: @peca %>

app/views/pecas/index.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
  <h1>Pecas</h1>
</div>

<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoInf">
  <div class="row">
    <div class="col-md-6 col-sm-8 col-xs-12">
      <div class="form-group">
              <%= form_tag pecas_path, :action => 'index', :method => 'get' do %>
              <p>
                <%= 'Digite o nome da peça para buscar' %>
                <br>
                <%= text_field_tag :search, params[:search], :class => "form-control", :style => "width: initial;"%>
                <%= submit_tag "Buscar", :nome => nil, class:"btn btn-primary" %>
              </p>
            <% end %>
  </div>
  </div>
<div class="col-md-6 col-sm-4 col-xs-12 text-right">
      <% if can? :create, Peca %>
      <div class="form-group">
      <br>
        <%= link_to 'Nova Peca', new_peca_path, class:"btn btn-default" %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
          <caption>Peças</caption>
            <tr>
              <th>Nome</th>
              <th>Caracteristica</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>


            <% @pecas.each do |peca| %>
              <tr>
                <td><%= link_to "#{peca.nome}", peca %></td>
                <td><%= peca.caracteristica %></td>
                <td><%= link_to 'Detalhes', peca, class: "btn-sm btn-info" %></td>
                <td><%= link_to 'Editar', edit_peca_path(peca), class: "btn-sm btn-default" %></td>
                <td><%= link_to 'Deletar', peca, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn-sm btn-danger" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @pecas, window: 2 %>
      </div>
    </div>
  </div>
</div>

app/views/pecas/new.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
    <h1>Nova Peca</h1>
</div>

<%= render 'form', peca: @peca %>

app/views/pecas/show.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoSup">
	<p>
	  <strong>Nome:</strong>
	  <%= @peca.nome %>
	</p>

	<p>
	  <strong>Caracteristica:</strong>
	  <%= @peca.caracteristica %>
	</p>

	<div class="row">
	  <div class="col-md-12 col-sm-12 col-xs-12">
		<%= link_to 'Editar', edit_peca_path(@peca), class:"btn btn-primary"%>
		<%= link_to 'Voltar', pecas_path, class:"btn btn-default"%>
	  </div>
	</div>

	<h2>Comentários</h2>
	<% @comments.each do |comment| %>
	  <div class="well">
	    <%= comment.user.name %> - <%= comment.created_at %> - 
	    <% if current_user.id == comment.user.id %>
	      <%= link_to 'Apagar', comment, method: :delete, data: { confirm: 'Tem certeza?' } %>
	    <% end %>
	    <p>
	    <%= comment.body %>
	  </div>
	<% end %>
	<%= paginate @comments, window: 2 %>

	<%= render partial: "comments/form", locals: {commentable: @peca} %>
	<!-- <%= render partial: "comments/comments", locals: {commentable: @peca} %>-->
</div>