config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :create, :edit, :show, :update, :destroy]
  match 'index' => "home#index", via: [:get]
  resources :ocorrencia do
    resources :comments, module: :ocorrencia
  end
  resources :termo_compromissos do
    resources :comments, module: :termo_compromissos
    member do
      # /agreements/:id/export
      get 'export'
    end
  end
  resources :manutencaos do
    resources :comments, module: :manutencaos
  end
  resources :estoque_pecas do
    get 'filed', on: :collection
    match 'arquivar' => "estoque_pecas#arquivar_peca", via: [:get]
    resources :comments, module: :estoque_pecas
  end
  resources :pecas do
    resources :comments, module: :pecas
  end
  resources :modelos do
    resources :comments, module: :modelos
  end
  resources :equipamentos do
  	match 'manutencaos' => "equipamentos#manutencao", via: [:get]
    resources :comments, module: :equipamentos
  end
  resources :servidors do 
    resources :comments, module: :servidors
  end
  resources :comments

  root "home#index"
end

app/models/manutencao.rb
class Manutencao < ApplicationRecord
	belongs_to :equipamento
	has_many :comments, as: :commentable

	def self.search(search)
	    if search
	      where(['"numOrdem" LIKE ?', "%#{search}%"])
	    else
	      all
	    end
  	end
end

app/controllers/manutencaos/comments_controller.rb
class Manutencaos::CommentsController < CommentsController
	before_action :set_commentable

	private
		def set_commentable
			@commentable = Manutencao.find(params[:manutencao_id])
		end
end

app/controllers/manutencaos_controller.rb
class ManutencaosController < ApplicationController
  load_and_authorize_resource
  before_action :set_manutencao, only: [:show, :edit, :update, :destroy]

  # GET /manutencaos
  # GET /manutencaos.json
  def index
    # @manutencaos = Manutencao.all
    @manutencaos = Manutencao.search(params[:search]).order(:numOrdem).page(params[:page]).per(10)
    # @manutencaos = Manutencao.find(params[:equipamento_id])
    # @manutencao = params[:equipamento_id]
  end

  # GET /manutencaos/1
  # GET /manutencaos/1.json
  def show
    @comments = @manutencao.comments.order("id DESC").page(params[:page]).per(3)
  end

  # GET /manutencaos/new
  def new
    @manutencao = Manutencao.new
  end

  # GET /manutencaos/1/edit
  def edit
  end

  # POST /manutencaos
  # POST /manutencaos.json
  def create
    @manutencao = Manutencao.new(manutencao_params)

    respond_to do |format|
      if @manutencao.save
        format.html { redirect_to @manutencao, notice: 'Manutencao was successfully created.' }
        format.json { render :show, status: :created, location: @manutencao }
      else
        format.html { render :new }
        format.json { render json: @manutencao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manutencaos/1
  # PATCH/PUT /manutencaos/1.json
  def update
    respond_to do |format|
      if @manutencao.update(manutencao_params)
        format.html { redirect_to @manutencao, notice: 'Manutencao was successfully updated.' }
        format.json { render :show, status: :ok, location: @manutencao }
      else
        format.html { render :edit }
        format.json { render json: @manutencao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manutencaos/1
  # DELETE /manutencaos/1.json
  def destroy
    @manutencao.destroy
    respond_to do |format|
      format.html { redirect_to manutencaos_url, notice: 'Manutencao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manutencao
      @manutencao = Manutencao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manutencao_params
      params.require(:manutencao).permit(:numOrdem, :descricao, :dataEntrada, :dataSaida, :status, :equipamento_id)
    end
end

app/helpers/manutencaos_helper.rb
module ManutencaosHelper
end

app/views/manutencaos/_form.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoInf">
  <div class="row">
    <%= form_with(model: @manutencao, local: true) do |form| %>
    <% if @manutencao.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(manutencao.errors.count, "error") %> prohibited this manutencao from being saved:</h2>

      <ul>
        <% manutencao.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="col-md-4 col-sm-4 col-xs-12 text-left">
      <div class="form-group">
        <%= form.label :equipamento_id, 'Patrimônio' %><br>
        <%= form.collection_select :equipamento_id, Equipamento.all, :id, :patrimonio, {}, {class: 'form-control'} %>
      </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12 text-left">
      <div class="form-group">
        <%= form.label :numOrdem, 'Número de Ordem' %><br>
        <%= form.text_field :numOrdem, class: "form-control" %>
      </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12 text-left">
      <div class="form-group">
        <%= form.label :descricao, 'Descrição' %><br>
        <%= form.text_field :descricao, class: "form-control" %>
      </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12 text-left">
      <div class="form-group">
        <%= form.label :dataEntrada, 'Data de Entrada' %><br>
        <%= form.date_select :dataEntrada, class: "form-control" %>
      </div>
    </div>

    <!--   <div class="col-md-4 col-sm-4 col-xs-12 text-left">
    <div class="form-group">
      <%= form.label :dataSaida, 'Data de Saída' %>
      <%= form.date_select :dataSaida, class: "form-control" %>
    </div>
  </div> -->

    <div class="col-md-4 col-sm-4 col-xs-12 text-left">
      <div class="form-group">
        <%= form.label :status, 'Status' %><br>
        <%= form.select :status, ['Aguardando técnico', 'Em manutenção', 'Concluído'], {}, {class: 'form-control'} %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <%= form.submit 'Salvar', class:"btn btn-primary" %>
          <%= link_to 'Voltar', manutencaos_path, class:"btn btn-default" %>
        </div>
      </div>
    </div>
    <% end %>

app/views/manutencaos/edit.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
    <h1>Editar Manutencao</h1>
</div>

<%= render 'form', manutencao: @manutencao %>

app/views/manutencaos/index.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
  <h1>Manutenções</h1>
</div>

<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoInf">
    <div class="row">
      <div class="col-md-6 col-sm-8 col-xs-12">
        <div class="form-group">
          <%= form_tag manutencaos_path, :action => 'index', :method => 'get' do %>
            <%= 'Digite o número de ordem para buscar' %>
            <br>
            <%= text_field_tag :search, params[:search], :class => "form-control", :style => "width: initial;" %>
            <%= submit_tag "Buscar", :numOrdem => nil, :class => "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6 col-sm-4 col-xs-12 text-right">
      <% if can? :create, Manutencao %>
      <div class="form-group">
          <br>
        <%= link_to 'Nova Manutenção', new_manutencao_path, class:"btn btn-default" %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
          <caption>Manutenções</caption>
            <tr>
              <th>Numero de ordem</th>
              <th>Patrimônio</th>
              <th>Descrição</th>
              <th>Data de entrada</th>
              <!-- <th>Data de saída</th> -->
              <th>Status</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @manutencaos.each do |manutencao| %>
              <tr>
                <td><%= link_to "#{manutencao.numOrdem}", manutencao %></td>
                <td><%= link_to manutencao.equipamento.patrimonio, equipamento_path("#{manutencao.equipamento_id}") %></td>
                <td><%= manutencao.descricao %></td>
                <td><%= manutencao.dataEntrada %></td>
                <!-- <td><%= manutencao.dataSaida %></td> -->
                <td><%= manutencao.status %></td>
                <td><%= link_to 'Detalhes', manutencao, class: "btn-sm btn-info" %></td>
                <td><%= link_to 'Editar', edit_manutencao_path(manutencao), class: "btn-sm btn-default" %></td>
                <td><%= link_to 'Deletar', manutencao, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn-sm btn-danger" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @manutencaos, window: 2 %>
      </div>
    </div>
  </div>
</div>

app/views/manutencaos/new.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1">
    <h1>Nova Manutenção</h1>
</div>

<%= render 'form', manutenção: @manutenção %>

app/views/manutencaos/show.html.erb
<div class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10 col-xs-offset-1 conteudoSup">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Numordem:</strong>
    <%= @manutencao.numOrdem %>
  </p>

  <p>
    <strong>Patrimônio:</strong>
    <%= @manutencao.equipamento_id %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= @manutencao.descricao %>
  </p>

  <p>
    <strong>Dataentrada:</strong>
    <%= @manutencao.dataEntrada %>
  </p>

<!--   <p>
    <strong>Datasaida:</strong>
    <%= @manutencao.dataSaida %>
  </p> -->

  <p>
    <strong>Status:</strong>
    <%= @manutencao.status %>
  </p>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <%= link_to 'Editar', edit_manutencao_path(@manutencao), class:"btn btn-primary"%>
      <%= link_to 'Voltar', manutencaos_path, class:"btn btn-default"%>
    </div>
  </div>

  <h2>Comentários</h2>
  <% @comments.each do |comment| %>
    <div class="well">
      <%= comment.user.name %> - <%= comment.created_at %> - 
      <% if current_user.id == comment.user.id %>
        <%= link_to 'Apagar', comment, method: :delete, data: { confirm: 'Tem certeza?' } %>
      <% end %>
      <p>
      <%= comment.body %>
    </div>
  <% end %>
  <%= paginate @comments, window: 2 %>

  <%= render partial: "comments/form", locals: {commentable: @manutencao} %>
  <!-- <%= render partial: "comments/comments", locals: {commentable: @manutencao} %>-->
</div>